### ISSUE TITLE
Q6 "Tables cannot have more than 0 materialized views, failed to create materialized view teams_by_wins on table teams"

### ISSUE THREAD

**Issue by deepakdubey123** [DataStax-Academy/workshop-cassandra-certification#3]
Hi,

Tried Q6 on Astra Cluster

`Connected to cndb at cassandra.ingress:9042.
[cqlsh 6.8.0 | DSE DB 4.0.0.6811 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
token@cqlsh> use admin;
token@cqlsh:admin> CREATE TABLE teams (
         ...     name TEXT PRIMARY KEY,
         ...     wins INT,
         ...     losses INT,
         ...     ties INT
         ... );
AlreadyExists: Table 'admin.teams' already exists
token@cqlsh:admin> CREATE MATERIALIZED VIEW IF NOT EXISTS
         ...     teams_by_wins AS
         ...     SELECT * FROM teams
         ...       WHERE wins IS NOT NULL AND name IS NOT NULL
         ...       PRIMARY KEY((wins), name);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Tables cannot have more than 0 materialized views, failed to create materialized view teams_by_wins on table teams"`

![image](https://user-images.githubusercontent.com/59557235/117405411-37d29680-af29-11eb-922b-8310dfb8a7a7.png)

**Comment by drchung5** [comment]
The original release of Astra supported materialized views. The new 'serverless' version does not currently support materialized views. This example works as expected on OSS Cassandra.

**Comment by SonicDMG** [comment]
Thank you for raising this issue as well Deepak. We appreciate you following up with feedback.
